name: news_retrofit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^8.1.5

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.7.0

  #dateFormat
  intl: ^0.19.0

  #Database
  floor: 1.5.0

  #make request to api
  retrofit: ^4.1.0

  #Hooks
  flutter_hooks: ^0.20.5

  #chached image
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: 8.1.0
  floor_generator: 1.5.0
  build_runner: 2.4.10

flutter:
  uses-material-design: true
